 {{--Ini adalah halaman isi sakramen Permandian--}}
@extends('template.utama')
@section('content')

	<h1>Sakramen Permandian</h1>
    <h2 class="">artikel 1 . Materi Dasar Sakramen Baptis </h2>
    <p><u><span class="">Baptisan dan hidup baru<br /></u>
                      </span></u><span class="">Banyak  orang Protestan mengatakan dan percaya bahwa Babtis hanya sebuah  simbol. Dalam Gereja Katolik Babtisan tidak hanya sebagai simbol tetapi  adalah sebuah sakramen. Babtisan (menurut Gereja Katolik) membuat kita  lahir baru. Dasar kitab suci dari ajaran tentang babtis ini cukup  banyak antara lain:</span></p>
    <p align="justify" class="">Yohanes 3:5 &quot;Aku berkata kepadamu, sesungguhnya jika seorang tidak dilahirkan dari <u> air dan Roh</u>,  ia tidak dapat masuk ke dalam Kerajaan Allah&quot; pada ayat ini Yesus  menekankan pentingnya Babtis sebagai jalan untuk masuk dalam Kerajaan  Allah.</p>
    <p align="justify" class="">dalam Kis 2:38 St. Petrus mengatakan &quot;Bertobatlah dan hendaklah kamu masing-masing memberi dirimu <u> dibaptis</u> dalam nama Yesus Kristus untuk <u> pengampunan dosamu, maka kamu akan menerima karunia Roh Kudus</u>.&quot; St. Petrus menekankan perlunya Babtis untuk pengampunan dosa dan syarat untuk menerima karunia Roh Kudus.</p>
    <p align="justify" class="">St. Paulus dalam Titus 3:5 &quot;pada waktu itu Dia telah menyelamatkan kita, bukan karena perbuatan baik yang telah kita lakukan, <u> tetapi karena rahmat-Nya oleh permandian kelahiran kembali dan oleh pembaharuan yang dikerjakan oleh Roh Kudus</u>&quot; lalu dalam Kis 22:16 &quot;Dan sekarang, mengapa engkau masih ragu-ragu? Bangunlah, <u> berilah dirimu dibaptis dan dosa-dosamu disucikan sambil berseru kepada nama Tuhan!</u>&quot;</p>
    <p align="justify" class="">Dari  beberapa ayat diatas jelaslah bahwa Sakramen babtis bukan hanya sebuah  lambang atau simbol (jikalau itu simbol untuk apa Para Rasul menekankan  perlunya Babtis?) tetapi Babtisan memang membuat kita lahir baru,  karena babtisan itu berhubungan erat sekali dengan Roh Kudus yang  membuat kita lahir baru. Bila kita perhatikan Yohanes 3:5 &quot;Aku berkata  kepadamu, sesungguhnya jika seorang tidak dilahirkan dari <u> air dan Roh</u>,  ia tidak dapat masuk ke dalam Kerajaan Allah&quot; kata &quot;air dan Roh&quot;  (Babtisan dan Roh Kudus) memiliki suatu hubungan erat yang tidak dapat  dipisahkan. Hubungan yang erat antara babtisan dan Roh Kudus yang tak  terpisahkan inilah yang membuat kita memperoleh hidup baru pada saat  kita dibabtis. karena hubungan yang erat antara Roh Kudus dan Babtisan  sehingga ketika Paulus berbicara mengenai babtisan ia tidak menyebut  Roh Kudus &quot;Atau tidak tahukah kamu, bahwa kita semua yang telah  dibaptis dalam Kristus, telah dibaptis dalam kematian-Nya? Dengan  demikian kita telah dikuburkan bersama-sama dengan Dia oleh baptisan  dalam kematian, supaya, sama seperti Kristus telah dibangkitkan dari  antara orang mati oleh kemuliaan Bapa, demikian juga kita akan hidup  dalam hidup yang baru.&quot; (Roma 6:3-4).</p>
    <p align="justify" class="">Babtisan bukan  perbuatan manusiawi belaka tetapi Babtis adalah tanda dan sarana Rahmat  Allah (yaitu kelahiran/hidup baru) dimana Allah berkarya melalui para  pelayan (Imam, Diakon, dll) yang membabtis. Jadi Babtisan adalah karya  Allah sendiri yang mencurahkan Roh Kudus-Nya. Babtisan tidak dapat  dibedakan/dipisahkan dari Iman kepada Yesus dan dari Pencurahan Roh  Kudus. Babtisan merupakan perwujudan iman seseorang kepada Yesus dan  Iman itu berhubungan dengan pencurahan Roh Kudus lihatlah pada1 Kor  12:3 &quot;Karena itu aku mau meyakinkan kamu, bahwa tidak ada seorangpun  yang berkata-kata oleh Roh Allah, dapat berkata: &quot;Terkutuklah Yesus!&quot;  dan tidak ada seorangpun, yang dapat mengaku: &quot;Yesus adalah Tuhan&quot;,  selain oleh Roh Kudus.&quot;</p>
    <p align="justify" class="">Dari uraian diatas jelaslah  bahwa Babtis bukan hanya sebuah simbol tetapi benar-benar membuat kita  lahir baru karena peranan dari Roh Kudus yang membuat kita lahir baru  didalam pembabtisan. oleh karena hal itulah St. Petrus menegaskan  perlunya babtisan bagi keselamatan &quot;Juga kamu sekarang diselamatkan  oleh kiasannya (kiasannya=air bah {lihat ayat sebelumnya untuk lebih  jelas}), yaitu baptisan--maksudnya bukan untuk membersihkan kenajisan  jasmani, melainkan untuk memohonkan hati nurani yang baik kepada  Allah--oleh kebangkitan Yesus Kristus&quot; (1 Pet 3:21)</p>
    <p align="justify" class=""><u>Babtis cara Selam<br />
        </u>Setelah  berbicara banyak mengenai Hakekat Babtis yang membuat kita lahir baru,  Ada baiknya kita membahas mengenai masalah Babtis selam. Babtis selam  dalam gereja Pantekosta&nbsp; dimutlakkan dan mereka terkadang (tidak  semuanya) mengatakan babtisan selain cara selam tidak sah.</p>
    <p align="justify" class="">secara  umum terkadang mereka mengajukan bukti dari Matius 3:16 &quot;Yesus segera  keluar dari air&quot; kata &quot;keluar dari air&quot; menurut mereka berarti Yesus  sebelumnya berada didalam air. Menurut kami kata &quot;keluar dari air&quot;  tidak menunjukkan berapa banyak bagian tubuh yang terendam. (yang  menarik bahwa lukisan kristen kuno tentang&nbsp; pembabtisan Yesus pada  Katakombe, dll pada jaman yang dekat dengan jaman para rasul  digambarkan bahwa Yesus masuk ke air hanya sebatas lutut)&nbsp;</p>
    <p align="justify" class="">Yang  agak Rumit disini adalah pembahasan dari kata Babtizo (kata Yunani  untuk membabtis) yang menurut mereka berarti &quot;menenggelamkan sesuatu  dalam air&quot;. Sebenarnya kata Babtizo memiliki beberapa arti yaitu  &quot;menenggelamkan&quot; dan arti yang lain &quot;mencelupkan&quot;. ada hal yang menarik  bahwa Lukas 11:38 &quot;Orang Farisi itu melihat hal itu dan ia heran,  karena Yesus tidak <em> mencuci</em> tangan-Nya sebelum makan&quot; kata  &quot;Mencuci&quot; dalam Lukas 11:38 dalam bahasa Yunani babtizo tetapi dalam  hal ini tentu bukan kata menenggelamkan, tetapi mungkin hanya  mencelupkan (dalam tradisi yahudi ada tempayan yang digunakan untuk  pembasuhan sebelum besantap) tetapi rasanya tidak etis dan tidak  higienis jika seseorang mencelupkan tangannya (yang kotor) kedalam  tempayan itu (sementara tempayan itu digunakan untuk pembasuhan tidak  hanya untuk satu orang) tentunya orang akan mengambil gayung dan  mengambil air dari tempayan itu lalu mengucurkannya ke tangan. Jadi  jelaslah penggunaan kata &quot;babtizo&quot; sangat fleksibel tidak hanya  menenggelamkan, oleh karena itu Tradisi Babtis Kristen sangat fleksibel  (<u>tidak hanya dengan diselam saja</u>) berikut kesaksian dari Dokumen  12 Rasul (berasal dari abad II M) mengatakan bahwa jika tidak ada air  yang cukup untuk membabtis maka pembabtisan dengan pengucuran airpun  adalah sah. hal itu juga ditegaskan dalam dokumen Didache (sekitar  tahun 100 Masehi) yang berisi hal yang sama dan juga pernyataan St.  Agustinus, sekedar pengetahuan Bahwa gereja Protestan yang termasuk  aliran utama (Lutheran, Calvinis) menggunakan cara Babtis mirip seperti  Katolik. Kita tahu kitab suci tidak memberikan petunjuk yang jelas  dengan cara apakah Para Rasul membabtis (apakah dengan cara selam,  dibasuh, atau dengan cara lain) tetapi kesaksian Yustinus Martir bahwa  pembabtisan dilakukan dengan cara &quot;masuk ke air&quot; dan menurut banyak  sejarah Gereja, pembabtisan dilakukan dengan cara menenggelamkan orang  dan ini merupakan cara Babtis pada Gereja perdana yang akhirnya  berevolusi menjadi Ritus yang lebih sederhana (untuk lebih jelasnya  lihat: <a href="sejarahpembatisan.html">Sakramen Babtis dan sejarah Perubahan Ritusnya</a>).  Cara (Ritus) apapun yang digunakan untuk pembabtisan tetap tidak  mengubah hakekat sakramen Babtis, bahkan menurut informasi di beberapa  Gereja Katolik di Amerika terdapat &quot;kolam&quot; untuk membabtis.&nbsp;</p>
    <p align="justify" class=""><u>Keselamatan tanpa babtis?<br />
        </u>Dalam  Dokumen Konsili Vatikan II Lumen Gentium No 16 dikatakan bahwa &quot;Mereka  yang tanpa bersalah tidak mengenal injil Kristus serta Gereja-Nya,  tetapi dengan tulus hati mencari Allah, dan berkat pengaruh rahmat  berusaha melaksanakan kehendak-Nya yang mereka kenal melalui suara hati  dengan perbuatan nyata, dapat memperoleh keselamatan kekal.&quot;. sekilas  ajaran itu bertentangan dengan 1 Tim 2:5 &quot;Karena Allah itu esa dan esa  pula Dia yang menjadi pengantara antara Allah dan manusia, yaitu  manusia Kristus Yesus&quot; ajaran Konsili Vatikan II menegaskan bahwa  mereka &quot;yang tanpa bersalah tidak mengenal injil Kristus&quot; bisa selamat  didasarkan karena Yesus menjadi tebusan bagi semua orang (lihat Mat  20:28; Mrk 10:45; 1Tim 2:6). Ajaran Konsili Vatikan II juga tidak  bertentangan dengan Mrk 16:15 dan Yoh 3:18 karena menurut pendapat kami  (yang bisa saja salah) Mrk 16:15 dan Yoh 3:18 tidak perlu ditafsirkan  secara harafiah dalam arti yang ketat kedua&nbsp; ayat itu menekankan  tentang perlunya iman dan babtisan agar orang dapat selamat, namun bagi  &quot;<u>yang tanpa bersalah tidak mengenal injil Kristus</u>&quot; masakah  mereka juga harus dihukum?. Ajaran Konsili Vatikan II ini tidak  mengakui bahwa semua agama itu sama, Gereja merasa perlu untuk  mewartakan injil dan kita wajib memperkenalkan Kristus yang adalah  jalan kebenaran dan Kehidupan dan Gereja sendiri memiliki kepenuhan  sarana-sarana keselamatan (lihat Redemptoris Missio 55, Ensiklik  Evangelii Nuntiandi, dokumen Konsili Vatikan II Digitatis Humanae 14,  Ad Gentes 6 dan 7, dll) oleh karena itulah Gereja tidak pernah  melupakan Perutusan agung yang diberikan Yesus &quot;Karena itu pergilah,  jadikanlah semua bangsa murid-Ku dan baptislah mereka dalam nama Bapa  dan Anak dan Roh Kudus, dan ajarlah mereka melakukan segala sesuatu  yang telah Kuperintahkan kepadamu. Dan ketahuilah, Aku menyertai kamu  senantiasa sampai kepada akhir zaman.&quot; (mat 28:19-20) dengan tujuan  memperkenalkan Kristus yang adalah jalan yang pasti dan singkat menuju  Rumah Bapa.</p>
@endsection